export const breedsMixedAlphbet = [
  'Affenpinscher',
  'Afghan Hound',
  'Airedale Terrier',
  'Akbash Dog',
  'Akita',
  'Alano Español',
  'Alaskan Klee Kai',
  'Alaskan Malamute',
  'Alpine Spaniel',
  'American Bulldog',
  'Ariege Pointer',
  'Ariegeois',
  'Armant',
  'Artois Hound',
  'Azawakh',
  'Bakharwal Dog',
  'Barbet',
  'Basenji',
  'Basset Hound',
  'Beagle',
  'Beagle-Harrier',
  'Bearded Collie',
  'Beauceron',  
  'Berger Picard',
  'Berner Laufhund',
  'Billy',
  'Bloodhound',
  'Blue Lacy',
  'Boerboel',  
  'Bolognese',
  'Border Collie',
  'Border Terrier',
  'Borzoi',
  'Boston Terrier',
  'Boxer',
  'Boykin Spaniel',
  'Bracco Italiano', 
  'Braque du Puy',
  'Braque Francais',
  'Briard',
  'Brittany',
  'Broholmer',
  'Bruno Jura Hound',
  'Bull and Terrier',
  'Bull Terrier',
  'Bulldog',
  'Bullenbeisser',
  'Bullmastiff',
  'Bully Kutta',
  'Burgos Pointer',
  'Cairn Terrier',
  'Canaan Dog',
  'Cane Corso',
  'Carolina Dog', 
  'Catahoula Cur',
  'Catalan Sheepdog',
  'Cesky Fousek',
  'Cesky Terrier',
  'Chien-gris',
  'Chihuahua',
  'Chinook',
  'Chippiparai',
  'Chow Chow',
  'Cierny Sery',
  'Clumber Spaniel',
  'Combai',
  'Coton de Tulear',
  'Cretan Hound',
  'Cursinu',
  'Dachshund',
  'Dalmatian',
  'Deutsche Bracke',
  'Dogo Argentino',
  'Dogo Cubano',
  'Drever',
  'Dunker',
  'Dutch Smoushond',
  'Elo',
  'English Foxhound',
  'English Mastiff',
  'English Setter',
  'English Shepherd',
  'Estonian Hound',
  'Eurasier',
  'Field Spaniel',
  'Fila Brasileiro',
  'Finnish Hound',
  'Finnish Lapphund',
  'Finnish Spitz',
  'French Bulldog',
  'French Spaniel',
  'German Pinscher',
  'German Shepherd',
  'German Spaniel',
  'German Spitz',
  'Giant Schnauzer',
  'Golden Retriever',
  'Gordon Setter',
  'Great Dane',
  'Great Pyrenees',
  'Greek Harehound',
  'Greenland Dog',
  'Greyhound',
  'Hamiltonstövare',
  'Hanover Hound',
  'Hare Indian Dog',
  'Harrier',
  'Havanese',
  'Hawaiian Poi Dog',
  'Hokkaido',
  'Hovawart',
  'Huntaway',
  'Hygenhund',
  'Ibizan Hound',
  'Indian Spitz',
  'Irish Setter',
  'Irish Terrier',
  'Irish Wolfhound',
  'Jagdterrier',
  'Jämthund',
  'Kai Ken',
  'Kaikadi',
  'Kanni',
  'Karst Shepherd',
  'Keeshond',
  'Kerry Beagle',
  'King Shepherd',
  'Kintamani',
  'Kishu',
  'Komondor',
  'Kooikerhondje',
  'Koolie',
  'Korean Jindo Dog',
  'Kromfohrländer',
  'Kumaon Mastiff',
  'Kurī',
  'Kuvasz',
  'Kyi-Leo',
  'Labrador Husky',
  'Lakeland Terrier',
  'Landseer',
  'Lapponian Herder',
  'Leonberger',
  'Lhasa Apso',
  'Lithuanian Hound',
  'Löwchen',
  'Maltese',
  'Maremma Sheepdog',
  'McNab',
  'Molossus',
  'Moscow Watchdog',
  'Moscow Water Dog',
  'Mountain Cur',
  'Mucuchies',
  'Mudhol Hound',
  'Mudi',
  'Newfoundland',
  'Norfolk Spaniel',
  'Norfolk Terrier',
  'Norrbottenspets',
  'Norwegian Buhund',
  'Norwich Terrier',
  'Otterhound',
  'Pachon Navarro',
  'Paisley Terrier',
  'Pandikona',
  'Papillon',
  'Pekingese',
  'Phalène',
  'Pharaoh Hound',
  'Picardy Spaniel',
  'Plott Hound',
  'Podenco Canario',
  'Polish Greyhound',
  'Polish Hound',
  'Pomeranian', 
  'Poodle',
  'Porcelaine',
  'Posavac Hound',
  'Pražský Krysařík',
  'Pudelpointer',
  'Pug',
  'Puli',
  'Pumi',
  'Pungsan Dog',
  'Pyrenean Mastiff',
  'Rajapalayam',
  'Rampur Greyhound',
  'Rat Terrier',
  'Rottweiler',
  'Rough Collie',
  'Russell Terrier',
  'Russian Spaniel',
  'Russian tracker',
  'Sabueso Español',
  'Sakhalin Husky',
  'Saluki',
  'Samoyed',
  'Sapsali',
  'Schapendoes',
  'Schillerstövare',
  'Schipperke',
  'Scotch Collie',
  'Scottish Terrier',
  'Sealyham Terrier',
  'Segugio Italiano',
  'Serbian Hound',
  'Shar Pei',
  'Shiba Inu',
  'Shih Tzu',
  'Shikoku',
  'Siberian Husky',
  'Silken Windhound',
  'Sinhala Hound',
  'Skye Terrier',
  'Sloughi',
  'Slovak Cuvac',
  'Smooth Collie',
  'Southern Hound',
  'Spanish Mastiff',
  'Spinone Italiano',
  'St. Bernard',
  'Stabyhoun',
  'Stephens Cur',
  'Sussex Spaniel',
  'Swedish Lapphund',
  'Swedish Vallhund',
  'Tahltan Bear Dog',
  'Taigan',
  'Talbot',
  'Tamaskan Dog',
  'Telomian',
  'Thai Ridgeback',
  'Tibetan Mastiff',
  'Tibetan Spaniel',
  'Tibetan Terrier',
  'Tornjak',
  'Tosa',
  'Toy Bulldog',
  'Toy Fox Terrier',
  'Treeing Cur',
  'Trigg Hound',
  'Tyrolean Hound',
  'Vizsla',
  'Volpino Italiano',
  'Weimaraner',
  'Welsh Sheepdog',
  'Welsh Terrier',
  'Wetterhoun',
  'Whippet',
  'White Shepherd',
  'Wire Fox Terrier',
  'Šarplaninac',
  'Abyssinian',
  'Aegean',
  'American Bobtail',
  'American Curl',
  'Arabian Mau',
  'Asian',
  'Australian Mist',
  'Balinese',
  'Bambino',
  'Bengal',
  'Birman',
  'Bombay',
  'British Longhair',
  'Burmese',
  'Burmilla',
  'Chartreux',
  'Chausie',
  'Cheetoh',
  'Cornish Rex',
  'Cymric',
  'Cyprus',
  'Devon Rex',
  'Donskoy',
  'Dragon Li',
  'Dwarf cat',
  'Egyptian Mau',
  'Exotic Shorthair',
  'Foldex',
  'German Rex',
  'Havana Brown',
  'Highlander',  
  'Japanese Bobtail',
  'Javanese',
  'Khao Manee',
  'Korat',
  'Korean Bobtail',
  'Korn Ja',
  'Kurilian Bobtail',
  'LaPerm',
  'Lykoi',
  'Maine Coon',
  'Manx',
  'Mekong Bobtail',
  'Minskin',
  'Munchkin',
  'Napoleon',
  'Nebelung',
  'Ocicat',
  'Ojos Azules',
  'Oregon Rex',
  'Oriental Bicolor',
  'PerFold',
  'Persian (Modern)',
  'Peterbald',
  'Pixie-bob',
  'Raas',
  'Ragamuffin',
  'Ragdoll',
  'Russian Blue',
  'Sam Sawet',
  'Savannah',
  'Scottish Fold',
  'Selkirk Rex',
  'Serengeti',
  'Serrade Petit',
  'Siamese',
  'Siberian',
  'Singapura',
  'Snowshoe',
  'Sokoke',
  'Sphynx',
  'Suphalak',
  'Thai',
  'Thai Lilac',
  'Tonkinese',
  'Toyger',
  'Turkish Angora',
  'Turkish Van',
  'Ukrainian Levkoy',
  'American Albino',
  'Abaco Barb',
  'Abtenauer',
  'Aegidienberger',
  'Akhal-Teke',
  'Albanian Horse',
  'Altai Horse',
  'Altèr Real',
  'Andalusian Horse',
  'Andravida Horse',
  'Anglo-Arabian',
  'Anglo-Kabarda',
  'Appaloosa',
  'AraAppaloosa',
  'Arabian Horse',
  'Ardennes Horse',
  'Asturcón',
  'Augeron',
  'Auvergne Horse',
  'Auxois',
  'Azerbaijan Horse',
  'Azteca Horse',
  'Baise Horse',
  'Bale',
  'Balearic Horse',
  'Balikun Horse',
  'Baluchi Horse',
  'Banker Horse',
  'Barb Horse',
  'Bardigiano',
  'Bashkir Curly',
  'Belgian Horse',
  'Bhutia Horse',
  'Blazer Horse',
  'Boerperd',
  'Borana',
  'Boulonnais Horse',
  'Brabant',
  'Brandenburger',
  'Breton Horse',
  'Brumby',
  'Budyonny Horse',
  'Burguete Horse',
  'Burmese Horse',
  'Calabrese Horse',
  'Camargue Horse',
  'Campeiro',
  'Campolina',
  'Canadian Horse',
  'Canadian Pacer',
  'Carthusian Horse',
  'Caspian Horse',
  'Castilian Horse',
  'Castillonnais',
  'Catria Horse',
  'Cerbat Mustang',
  'Chickasaw Horse',
  'Choctaw Horse',
  'Cleveland Bay',
  'Clydesdale Horse',
  'Cob',
  'Colorado Ranger',
  'Comtois Horse',
  'Corsican Horse',
  'Cretan Horse',
  'Criollo Horse',
  'Cuban Criollo',
  'Curly Horse',
  'Czech Warmblood',
  'Daliboz',
  'Danish Warmblood',
  'Don',
  'Dongola Horse',
  'Draft Trotter',
  'Dutch Warmblood',
  'Dzungarian Horse',
  'East Bulgarian',
  'Estonian Draft',
  'Estonian Horse',
  'Falabella',
  'Faroese',
  'Finnhorse',
  'Fjord Horse',
  'Fleuve',
  'Foutanké',
  'Freiberger',
  'French Trotter',
  'Friesian Cross',
  'Friesian Horse',
  'Galiceño',
  'Gelderland Horse',
  'German Warmblood',
  'Giara Horse',
  'Gidran',
  'Groningen Horse',
  'Gypsy Horse',
  'Hackney Horse',
  'Haflinger',
  'Hanoverian Horse',
  'Heck Horse',
  'Heihe Horse',
  'Henson Horse',
  'Hequ Horse',
  'Hirzai',
  'Hispano-Bretón',
  'Holsteiner Horse',
  'Horro',
  'Icelandic Horse',
  'Iomud',
  'Irish Draught',
  'Italian Trotter',
  'Jaca Navarra',
  'Jeju Horse',
  'Jutland Horse',
  'Kabarda Horse',
  'Kafa',
  'Kaimanawa Horses',
  'Kalmyk Horse',
  'Karabair',
  'Karabakh Horse',
  'Karachai Horse',
  'Karossier',
  'Kathiawari',
  'Kazakh Horse',
  'Kiger Mustang',
  'Kinsky Horse',
  'Kisber Felver',
  'Kiso Horse',
  'Kladruber',
  'Knabstrupper',
  'Konik',
  'Kundudo',
  'Kustanair',
  'Kyrgyz Horse',
  'Latvian Horse',
  'Lipizzan',
  'Lokai',
  'Losino Horse',
  'Lusitano',
  'Lyngshest',
  "M'Bayar",
  "M'Par",
  'Mallorquín',
  'Malopolski',
  'Mangalarga',
  'Maremmano',
  'Marismeño Horse',
  'Marsh Tacky',
  'Marwari Horse',
  'Mecklenburger',
  'Međimurje Horse',
  'Menorquín',
  'Mérens Horse',
  'Messara Horse',
  'Metis Trotter',
  'Miniature Horse',
  'Misaki Horse',
  'Monchina',
  'Mongolian Horse',
  'Monterufolino',
  'Morab',
  'Morgan Horse',
  'Moyle Horse',
  'Murakoz Horse',
  'Murgese',
  'Mustang Horse',
  'Nangchen Horse',
  'Nez Perce Horse',
  'Nivernais Horse',
  'Nokota Horse',
  'Noma',
  'Nonius Horse',
  'Nooitgedachter',
  'Nordlandshest',
  'Noriker Horse',
  'Norman Cob',
  'Norwegian Fjord',
  'Novokirghiz',
  'Oberlander Horse',
  'Oldenburg Horse',
  'Orlov trotter',
  'Ostfriesen',
  'Paint',
  'Pampa Horse',
  'Paso Fino',
  'Pentro Horse',
  'Percheron',
  'Persano Horse',
  'Peruvian Paso',
  'Pintabian',
  'Pleven Horse',
  'Poitevin Horse',
  'Posavac Horse',
  'Pottok',
  'Qatgani',
  'Quarab',
  'Quarter Horse',
  'Racking Horse',
  'Retuerta Horse',
  'Riwoche Horse',
  'Rottaler',
  'Russian Don',
  'Russian Trotter',
  'Saddlebred',
  'Salerno Horse',
  'Samolaco Horse',
  'Sarcidano Horse',
  'Selale',
  'Sella Italiano',
  'Selle Français',
  'Shagya Arabian',
  'Shan Horse',
  'Shire Horse',
  'Silesian Horse',
  'Sokolsky Horse',
  'Sorraia',
  'Spanish Barb',
  'Spanish Mustang',
  'Spanish Tarpan',
  'Spiti Horse',
  'Suffolk Punch',
  'Swedish Ardennes',
  'Swiss Warmblood',
  'Taishū Horse',
  'Takhi',
  'Tawleed',
  'Tchernomor',
  'Tersk Horse',
  'Thoroughbred',
  'Tiger Horse',
  'Tinker Horse',
  'Tolfetano',
  'Tori Horse',
  'Trait Du Nord',
  'Trakehner',
  'Tsushima',
  'Tuigpaard',
  'Unmol Horse',
  'Uzunyayla',
  'Ventasso Horse',
  'Vlaamperd',
  'Vyatka',
  'Waler',
  'Waler Horse',
  'Walkaloosa',
  'Warlander',
  'Warmblood',
  'Welsh Cob',
  'Wielkopolski',
  'Württemberger',
  'Xilingol Horse',
  'Yakutian Horse',
  'Yili Horse',
  'Yonaguni Horse',
  'Zaniskari',
  'Zhemaichu',
  'Zweibrücker',
  'American',
  'American Sable',
  'Argente Brun',
  'Belgian Hare',
  'Beveren',
  'Blance de Hotot',
  'Britannia Petite',
  'Californian',
  'Checkered Giant',
  'Cinnamon',
  "Creme D'argent",
  'Dutch',
  'Dwarf Hotot',
  'English Angora',
  'English Lop',
  'English Spot',
  'Flemish Giant',
  'Florida White',
  'French Angora',
  'French Lop',
  'Giant Angora',
  'Giant Chinchilla',
  'Harlequin',
  'Havana',
  'Himalayan',
  'Holland Lop',
  'Jersey Wooly',
  'Lilac',
  'Lionhead',
  'Mini Lop',
  'Mini Rex',
  'Mini Satin',
  'Netherland Dwarf',
  'New Zealand',
  'Palomino',
  'Polish',
  'Rex',
  'Rhinelander',
  'Satin',
  'Satin Angora',
  'Silver',
  'Silver Fox',
  'Silver Marten',
  'Tan',
  'Thrianta',
  'Anadolu Pony',
  'Ariegeois Pony',
  'Assateague Pony',
  'Asturian Pony',
  'Australian Pony',
  'Bali Pony',
  'Bashkir Pony',
  'Basque Pony',
  'Basuto Pony',
  'Batak Pony',
  'Bhutia Pony',
  'Bosnian Pony',
  'Burmese Pony',
  'Carpathian Pony',
  'Caspian Pony',
  'Chinese Guoxia',
  'Coffin Bay Pony',
  'Connemara Pony',
  'Dales Pony',
  'Dartmoor Pony',
  'Deli Pony',
  'Dülmen Pony',
  'Eriskay Pony',
  'Esperia Pony',
  'Exmoor Pony',
  'Faroe Pony',
  'Fell Pony',
  'Flores Pony',
  'Galician Pony',
  'Garrano',
  'Gayoe',
  'Gotland Pony',
  'Guangxi',
  'Guizhou Pony',
  'Gǔo-xìa Pony',
  'Hackney Pony',
  'Highland Pony',
  'Hokkaido Pony',
  'Hucul Pony',
  'Hunter Pony',
  'Icelandic Pony',
  'Java Pony',
  'Kerry bog Pony',
  'Landais Pony',
  'Lijiang Pony',
  'Linxian',
  'Lundy Pony',
  'Majorera Donkey',
  'Maltese Donkey',
  'Manipuri Pony',
  'Mannar',
  'Maryisltaya',
  'Masai',
  'Masri',
  'Merens Pony',
  'Merzifon',
  'Miniature Donkey',
  'Miranda Donkey',
  'Miyako Pony',
  'Moldavian Local',
  'Moroccan',
  'Mula',
  'Muscat',
  'Narym Pony',
  'National Genatic',
  'New Forest Pony',
  'Noma Pony',
  'Nordestina',
  'Norman Donkey',
  'Northlands Pony',
  'Ob Pony',
  'Ogaden',
  'Pantesco',
  'Paulista',
  'Pega',
  'Peneia Pony',
  'Peruano',
  'Petiso Argentino',
  'Pindos Pony',
  'Poitevin',
  'Poitou Donkey',
  'Poney Mousseye',
  'Ponui Donkey',
  'Provence Donkey',
  'Puttalam Buruwa',
  'Pyrenean Donkey',
  'Qinghai',
  'Qinqyang',
  'Qirmani',
  'Quarter Pony',
  'Qubressy',
  'Ragusano Donkey',
  'Riding Pony',
  'Riffawi',
  'Romagnolo Donkey',
  'Romanian Donkey',
  'Saidi',
  'Sandalwood Pony',
  'Sardinian Donkey',
  'Sardinian Pony',
  'Sennar',
  'Shanbei',
  'Shetland Pony',
  'Sibbianl',
  'Skogsruss',
  'Skyros Pony',
  'Somali',
  'South-West',
  'Sperki',
  'Spiti Pony',
  'Spotted',
  'Standard',
  'Subei',
  'Sudanese Pack',
  'Syrian',
  'Tadzhikskaya',
  'Taihang',
  'Tibetan',
  'Tibetan Pony',
  'Timor Pony',
  'Tokara Pony',
  'Toposa',
  'Tswana',
  'Tunisian',
  'Turkmenskaya',
  'Uzbekskaya',
  'Viterbese',
  'Vyatka Horse',
  'Welara',
  'Welsh Pony',
  'Weser-Ems Pony',
  'Xinjiang',
  'Yakut Pony',
  'Yangyuan',
  'Yonaguni',
  'Yunnan',
  'Zamorano-Leonés',
  'Žemaitukas',
  'Zhumd',
  'Crested shelduck',
  'Campbell teal',
  "Baer's pochard",
  'Andaman teal',
  'Laysan duck',
  'Auckland teal',
  "Bernier's teal",
  'Blue duck',
  'Brown teal',
  "Meller's duck",
  'Hawaiian duck',
  'Nene',
  "Salvadori's teal",
  'Philippine duck',
  'Maccoa duck',
  'Andean teal',
  'Coscoroba swan',
  'Orinoco goose',
  'Sunda teal',
  'Blue-billed duck',
  "Hartlaub's duck",
  "Eaton's pintail",
  'Marbled duck',
  'Masked duck',
  'Muscovy duck',
  'Swan goose',
  'Mandarin duck',
  'Emperor goose',
  'Falcated duck',
  'Black swan',
  'Smew',
  'Ruddy shelduck',
  'Whooper swan',
  'Harlequin duck',
  'Surf scoter',
  'Tundra swan',
  'Spectacled eider',
  'Velvet scoter',
  'Black scoter',
  'Brant goose',
  'Common shelduck',
  'Mute swan',
  'King eider',
  'Cackling goose',
  'Magpie goose',
  'Grey teal',
  'Greylag goose',
  'Bufflehead',
  'Greater scaup',
  'Common scoter',
  'Common merganser',
  'Common pochard',
  'Common goldeneye',
  'Garganey',
  'Tufted duck',
  'Eurasian wigeon',
  'Common eider',
  'Gadwall',
  'Northern pintail',
  'Long-tailed duck',
  'Mallard',
];
const breedsByAlphbet = [...breedsMixedAlphbet].sort();
export const breeds = ['', ...breedsByAlphbet, 'other'];
export const getBreed = query =>
  breeds.filter(breed => breed.includes(query)) || ['Idk'];